### ISSUE TITLE
Ammonite website not rendering correctly

### ISSUE THREAD

**Issue by agam** [com-lihaoyi/Ammonite#1086] opened 2020-05-28 04:50 UTC
(Opening an issue, based on this forum post: https://users.scala-lang.org/t/ammonite-website-not-rendering-correctly/6080)

Recently discovered Ammonite and liking it, and following along with the examples – although I have to rely on https://github.com/lihaoyi/Ammonite/blob/c25dc3aa46bd409fad147aababa2186cfd51b7d8/readme/Shell.scalatex#L116
because for some reason the website isn’t rendering properly. I’m guessing it’s something to do with the @compare there but I’m not sure.

Here’s a comparison of a certain section (below) and what I see (attached), hopefully someone has clues on how to fix this.

```
 @p
        Here is how to find the largest 3 files in a given directory tree:

      @compare(
        "find ./repl/src -ls | sort -nrk 7 | head -3",
        "ls.rec! wd/'amm/'src | (x => x.size -> x.last) sortBy (-_._1) take 3"
      )
```

![98e9518b81109f15ec8bdceb6aa199f9da0c3e92](https://user-images.githubusercontent.com/315427/83100140-089e7e80-a064-11ea-92a5-f3e76e5170b8.png)

**Comment by sharon-wang** [comment] 2021-08-05 15:47
I'm seeing a similar issue. https://github.com/com-lihaoyi/Ammonite/issues/1132 seems like a duplicate of the problem I'm seeing, where the bash/ammonite comparison section is missing. Additionally, one of the "largest 3 files" is missing.

![image](https://user-images.githubusercontent.com/25834218/128379231-38fc2392-119e-4b2f-97eb-3026a057c1d9.png)

Inspecting the page, we can see the missing content isn't getting rendered:
![image](https://user-images.githubusercontent.com/25834218/128379590-57f9fd75-8832-40b7-9156-277dfffffe9e.png)

Also looks to me that `@compare` is not handled correctly.
https://github.com/com-lihaoyi/Ammonite/blob/4824b429cec757cc2d053b0b8ee876cc7389658a/readme/Shell.scalatex#L141-L144

There was some effort recently to fix this: https://github.com/com-lihaoyi/Ammonite/pull/1173, but it seems the core problem causing this issue hasn't been identified yet.

**Closed** 2021-08-30 14:00 UTC
