### ISSUE TITLE
Documentation comparing bash and ammonite is broken

### ISSUE THREAD

**Issue by oswaldo** [com-lihaoyi/Ammonite#1121] opened 2020-11-13 16:33 UTC
I created a ticket in scalatex as I believe this is the result of some glitch there: https://github.com/lihaoyi/Scalatex/issues/73

So here is a heads up that beginner users might get a bad experience with the documentation at the moment as the first lines of each example comparing bash and ammonite is missing in the ammonite side, which is particularly unfortunate.

If my hypothesis is right, once scalatex is fixed, ammonite documentation should be fine again

**Comment by sake92** [comment] 2021-03-23 23:12
@oswaldo It's not Scalatex problem, it's here: https://github.com/com-lihaoyi/Ammonite/blob/master/readme/Sample.scala#L174-L192  
PR is very welcome! :)

**Comment by sake92** [comment] 2021-03-23 23:22
Duplicate of #1086

**Closed by sake92** 2021-03-23 23:22 UTC
